#!/bin/sh

set -e

update-alternatives --install /usr/games/nethack nethack \
  /usr/lib/games/nethack/nethack-console.sh 50

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section

