#!/bin/sh

# Nethack post-remove script for Debian
#
# Ben Gertzfield (che@debian.org) 29 July 1997
# Copyright 1997 Ben Gertzfield. This script is released under the
# GNU General Public License, version 2 or later.

# Updated 13 October 2003 to move the debhelper above the save-files
# purge (seems to be reading from stdin, seeing the "Purging" echo
# as a command)

# Updated 18 August 1998 to rm -rf the score/save directory on a purge,
# added debhelper comments

set -e

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section
# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d nethack-common remove >/dev/null || exit $?
fi
# End automatically added section


if [ "$1" = "purge" ]; then
    echo -n "Purging high-scores and save-files for Nethack... "
    rm -rf /var/games/nethack/
    echo "done."
fi

