#!/bin/sh
set -e
# Automatically added by dh_installxfonts
if [ -x "`which update-fonts-dir 2>/dev/null`" ]; then
	update-fonts-dir --x11r7-layout misc
fi
# End automatically added section
# Automatically added by dh_installmenu
if [ -x "`which update-menus 2>/dev/null`" ]; then update-menus ; fi
# End automatically added section
